apiVersion: apps/v1
kind: Deployment
metadata:
  name: house-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: house-app
  template:
    metadata:
      labels:
        app: house-app
    spec:
      containers:
      - name: house-api
        image: house-predictor:v1
        imagePullPolicy: Never  # <--- Crucial! Tells K8s to use the local image we just loaded
        ports:
        - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: house-app-service
spec:
  selector:
    app: house-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: NodePort